heightlimit: 50
loglimit: 500
popleaves: 2
sound: true
effect: true
popinterval: -1
moredamagetotools: 0
interruptiftoolwillbreak: true
considertoolenchantment: true
autoreplant: -1
allowedtools:
- 'GOLD_AXE'
- 'WOOD_AXE'
- 'STONE_AXE'
- 'IRON_AXE'
- 'DIAMOND_AXE'