name: ChopTreeW
main: me.crafter.mc.choptreew.ChopTreeW
author: connection_lost
version: 1.4
description: >
             0w0
commands:
   choptree:
      permission: choptree.chop
      usage: |
         /choptree