name: ChopTreeW
main: me.crafter.mc.choptreew.ChopTreeW
author: connection_lost
version: 1.3
description: >
             0w0
commands:
   choptree:
      permission: choptree.admin
      usage: |
         /choptree